services:
  gamex-api-gateway-5071:
    container_name: gamex-api-gateway-5071
    labels:
      - gamex.api.gateway
    hostname: gamex-api-gateway
    image: gamex-api-gateway-5071
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - ASPNETCORE_HTTP_PORTS=3100
      - ASPNETCORE_HTTP_PORTS=3101
      - TZ=Asia/Dhaka
    ports:
      - "5071:3100"
    restart: always
    volumes:
      - log_data:/log

    logging:
        options:
          max-size: 10m
    deploy:
      resources:
        limits:
          memory: 512M       # Limit memory usage to 512MB
          cpus: '0.50'       # Limit CPU usage to 50% of one core
  
volumes:
  log_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/gamex/app_logs