services:
  gamex-api-gateway-5071:
    container_name: gamex-api-gateway-5071
    labels:
      - gamex.api.gateway
    hostname: gamex-api-gateway
    image: gamex-api-gateway-5071
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - ASPNETCORE_HTTP_PORTS=3100
      - ASPNETCORE_HTTP_PORTS=3101
      - DEBUG=true
      - TZ=Asia/Dhaka
    ports:
      - "5071:3100"
    restart: always
    
    logging:
        options:
          max-size: 10m
    volumes:
      - log_data:/log
    deploy:
      resources:
        limits:
          memory: 10G       # Limit memory usage to 10GB
          cpus: '8'       # Limit CPU usage to 8 cores
  
volumes:
  log_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\PROJECTS\gamex\Storages\Logs