services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"     
    deploy:
      resources:
        limits:
          memory: 100M       # Limit memory usage to 1GB
          cpus: '0.5'      # Limit CPU usage to 1.5 core
 
    restart: always
    volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=gakk@123


